apiVersion: v1
kind: ServiceAccount
metadata:
  name: order-placement-v1-1
  labels:
    app.kubernetes.io/instance: globex-app-user1
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: order-placement-v1-1
    app.kubernetes.io/part-of: globex-app-user1
    app.kubernetes.io/version: 1.0.0

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-placement-v1-1
  labels:
    app.kubernetes.io/instance: globex-app-user1
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: order-placement
    app.kubernetes.io/part-of: globex-app-user1
    app.kubernetes.io/version: 1.0.0
    app.openshift.io/runtime: quarkus
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: order-placement-v1-1
      app.kubernetes.io/part-of: globex-app-user1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: order-placement-v1-1
        app.kubernetes.io/part-of: globex-app-user1
    spec:
      serviceAccountName: order-placement-v1-1
      containers:
        - name: order-placement-v1-1
          image: 'quay.io/rh_soln_pattern_api_versioning/order-placement:v1.1'
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env: 
            - name: JSON_SCHEMA
              value: order-placement-payload_v1.1.json
            - name: REGISTRY_URL
            - name: REGISTRY_GROUPID
              value: globex
            - name: REGISTRY_ARTIFACTID
              value: OrderPlacementJsonSchemaAPI
            - name: REGISTRY_ARTIFACTID_VERSION
              value: "2"
          livenessProbe:
            httpGet:
              path: /q/health/live
              port: http
              scheme: HTTP
            initialDelaySeconds: 30
            timeoutSeconds: 3
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /q/health/ready
              port: http
              scheme: HTTP
            initialDelaySeconds: 5
            timeoutSeconds: 3
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          resources:
            limits:
              cpu: 100m
              memory: 250Mi
            requests:
              cpu: 100m
              memory: 128Mi
          volumeMounts:
            - mountPath: /deployments/config
              name: config
      volumes:
        - name: config
          secret:
            secretName: order-placement
            defaultMode: 420

---

apiVersion: v1
kind: Service
metadata:
  name: order-placement-v1-1
  labels:
    app.kubernetes.io/instance: globex-app-user1
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: order-placement-v1-1
    app.kubernetes.io/part-of: globex-app-user1
    app.kubernetes.io/version: 1.0.0
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: order-placement-v1-1
    app.kubernetes.io/part-of: globex-app-user1

  